"""Guard against Alembic migrations drifting from the ORM models.

`Base.metadata.create_all` is the source of truth for the runtime schema, and the
Alembic migration chain is autogenerated to match it. If a model changes without a
matching migration, ``alembic upgrade head`` would yield a schema that differs from
``create_all`` — this test fails loudly so the migration gets regenerated
(``uv run alembic revision --autogenerate``). See next_phase.md §4 P2.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config as AlembicConfig
from alembic.migration import MigrationContext
from sqlalchemy import create_engine

from mastodon_mock.db import models  # noqa: F401  (register models on Base.metadata)
from mastodon_mock.db.base import Base

_REPO_ROOT = Path(__file__).resolve().parents[1]

# Diffs Alembic may report that are noise on SQLite rather than real drift:
# SQLite has limited ALTER support, so implicitly-named constraints (FKs) and
# index/variant details can show up even when the logical schema matches.
_IGNORED_DIFF_TYPES = {
    "add_constraint",
    "remove_constraint",
    "add_index",
    "remove_index",
}


def _alembic_config(db_url: str) -> AlembicConfig:
    cfg = AlembicConfig(str(_REPO_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(_REPO_ROOT / "mastodon_mock" / "alembic"))
    cfg.set_main_option("sqlalchemy.url", db_url)
    return cfg


def _significant(diffs: list[Any]) -> list[Any]:
    """Drop SQLite-only constraint/index noise from a compare_metadata diff."""
    out = []
    for diff in diffs:
        # Each diff is either a tuple ``(op, ...)`` or a list of such tuples.
        entries = diff if isinstance(diff, list) else [diff]
        for entry in entries:
            op = entry[0] if isinstance(entry, tuple) else None
            if op in _IGNORED_DIFF_TYPES:
                continue
            out.append(entry)
    return out


def test_migrations_match_models(tmp_path: Path) -> None:
    db_path = tmp_path / "drift.db"
    db_url = f"sqlite:///{db_path}"

    # Build the schema purely from the migration chain.
    command.upgrade(_alembic_config(db_url), "head")

    # Compare the migrated DB against the ORM metadata; any non-trivial diff is drift.
    engine = create_engine(db_url)
    try:
        with engine.connect() as conn:
            ctx = MigrationContext.configure(conn)
            diffs = compare_metadata(ctx, Base.metadata)
    finally:
        engine.dispose()

    significant = _significant(diffs)
    assert not significant, (
        "Alembic migrations have drifted from the ORM models. Regenerate with "
        "`uv run alembic revision --autogenerate -m '<msg>'`. Diff:\n" + "\n".join(repr(d) for d in significant)
    )
