"""add followed_tags and status quote state/policy

Revision ID: 4876ba204456
Revises: 6b88d352c69c
Create Date: 2026-06-15 11:41:06.516728
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4876ba204456'
down_revision: str | None = '6b88d352c69c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followed_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_followed_tag')
    )
    with op.batch_alter_table('followed_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followed_tags_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followed_tags_name'), ['name'], unique=False)

    # server_default lets the non-nullable columns apply to existing rows; the
    # ORM supplies its own Python-side default for new rows.
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_state', sa.String(), nullable=False, server_default='accepted'))
        batch_op.add_column(
            sa.Column('quote_approval_policy', sa.String(), nullable=False, server_default='public')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.drop_column('quote_approval_policy')
        batch_op.drop_column('quote_state')

    with op.batch_alter_table('followed_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followed_tags_name'))
        batch_op.drop_index(batch_op.f('ix_followed_tags_account_id'))

    op.drop_table('followed_tags')
    # ### end Alembic commands ###
