"""add push_subscriptions table

Revision ID: 51ee74b06b22
Revises: b2d5f8a3c014
Create Date: 2026-06-20 09:52:45.665216
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "51ee74b06b22"
down_revision: str | None = "b2d5f8a3c014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("token_id", sa.BigInteger(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("server_key", sa.String(), nullable=False),
        sa.Column("alerts", sa.JSON(), nullable=False),
        sa.Column("policy", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["oauth_tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("push_subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_push_subscriptions_token_id"), ["token_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("push_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_push_subscriptions_token_id"))

    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
