"""add admin moderation tables and account fields

Revision ID: 6b88d352c69c
Revises: 7cb2c44ee202
Create Date: 2026-06-15 09:56:51.471891
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b88d352c69c'
down_revision: str | None = '7cb2c44ee202'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_canonical_email_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_email_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_canonical_email_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_canonical_email_blocks_canonical_email_hash'), ['canonical_email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_canonical_email_blocks_created_at'), ['created_at'], unique=False)

    op.create_table('admin_domain_allows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_domain_allows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_domain_allows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_domain_allows_domain'), ['domain'], unique=False)

    op.create_table('admin_domain_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reject_media', sa.Boolean(), nullable=False),
    sa.Column('reject_reports', sa.Boolean(), nullable=False),
    sa.Column('private_comment', sa.Text(), nullable=True),
    sa.Column('public_comment', sa.Text(), nullable=True),
    sa.Column('obfuscate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_domain_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_domain_blocks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_domain_blocks_domain'), ['domain'], unique=False)

    op.create_table('admin_email_domain_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_email_domain_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email_domain_blocks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_email_domain_blocks_domain'), ['domain'], unique=False)

    op.create_table('admin_ip_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_ip_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_ip_blocks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_ip_blocks_ip'), ['ip'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('forwarded', sa.Boolean(), nullable=False),
    sa.Column('status_ids', sa.JSON(), nullable=False),
    sa.Column('rule_ids', sa.JSON(), nullable=False),
    sa.Column('action_taken', sa.Boolean(), nullable=False),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_account_id', sa.BigInteger(), nullable=True),
    sa.Column('action_taken_by_account_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['action_taken_by_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['assigned_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_account_id'), ['target_account_id'], unique=False)

    # Non-nullable columns carry a server_default so the ALTER succeeds on
    # tables with existing rows; the ORM applies its own Python-side defaults
    # for new rows, so the schemas stay equivalent.
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ip', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, server_default='user'))
        batch_op.add_column(sa.Column('locale', sa.String(), nullable=False, server_default='en'))
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('silenced', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('sensitized', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('invite_request', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('invite_request')
        batch_op.drop_column('sensitized')
        batch_op.drop_column('suspended')
        batch_op.drop_column('silenced')
        batch_op.drop_column('disabled')
        batch_op.drop_column('approved')
        batch_op.drop_column('confirmed')
        batch_op.drop_column('locale')
        batch_op.drop_column('role')
        batch_op.drop_column('ip')
        batch_op.drop_column('email')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_target_account_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_reports_account_id'))

    op.drop_table('reports')
    with op.batch_alter_table('admin_ip_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_ip_blocks_ip'))
        batch_op.drop_index(batch_op.f('ix_admin_ip_blocks_created_at'))

    op.drop_table('admin_ip_blocks')
    with op.batch_alter_table('admin_email_domain_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_email_domain_blocks_domain'))
        batch_op.drop_index(batch_op.f('ix_admin_email_domain_blocks_created_at'))

    op.drop_table('admin_email_domain_blocks')
    with op.batch_alter_table('admin_domain_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_domain_blocks_domain'))
        batch_op.drop_index(batch_op.f('ix_admin_domain_blocks_created_at'))

    op.drop_table('admin_domain_blocks')
    with op.batch_alter_table('admin_domain_allows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_domain_allows_domain'))
        batch_op.drop_index(batch_op.f('ix_admin_domain_allows_created_at'))

    op.drop_table('admin_domain_allows')
    with op.batch_alter_table('admin_canonical_email_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_canonical_email_blocks_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_canonical_email_blocks_canonical_email_hash'))

    op.drop_table('admin_canonical_email_blocks')
    # ### end Alembic commands ###
