"""initial schema

Revision ID: 7afb4f53fee4
Revises:
Create Date: 2026-06-14 16:13:42.149793
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7afb4f53fee4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("bot", sa.Boolean(), nullable=False),
        sa.Column("discoverable", sa.Boolean(), nullable=True),
        sa.Column("group", sa.Boolean(), nullable=False),
        sa.Column("indexable", sa.Boolean(), nullable=False),
        sa.Column("hide_collections", sa.Boolean(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("header_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("default_privacy", sa.String(), nullable=False),
        sa.Column("default_sensitive", sa.Boolean(), nullable=False),
        sa.Column("default_language", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "domain", name="uq_account_username_domain"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_username"), ["username"], unique=False)

    op.create_table(
        "oauth_apps",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("redirect_uris", sa.JSON(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
    )
    op.create_table(
        "polls",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("multiple", sa.Boolean(), nullable=False),
        sa.Column("hide_totals", sa.Boolean(), nullable=False),
        sa.Column("expired", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_reads",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "conversation_id", name="uq_conversation_read"),
    )
    with op.batch_alter_table("conversation_reads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversation_reads_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversation_reads_conversation_id"), ["conversation_id"], unique=False)

    op.create_table(
        "domain_blocks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("domain_blocks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_domain_blocks_account_id"), ["account_id"], unique=False)

    op.create_table(
        "filters",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("filter_action", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("filters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_filters_account_id"), ["account_id"], unique=False)

    op.create_table(
        "markers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("timeline", sa.String(), nullable=False),
        sa.Column("last_read_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "timeline", name="uq_marker"),
    )
    with op.batch_alter_table("markers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_markers_account_id"), ["account_id"], unique=False)

    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("app_id", sa.BigInteger(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=True),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["oauth_apps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
    )
    op.create_table(
        "poll_options",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("poll_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["polls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "poll_votes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("poll_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("option_position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["polls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("poll_votes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_poll_votes_poll_id"), ["poll_id"], unique=False)

    op.create_table(
        "relationships",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_account_id", sa.BigInteger(), nullable=False),
        sa.Column("target_account_id", sa.BigInteger(), nullable=False),
        sa.Column("following", sa.Boolean(), nullable=False),
        sa.Column("showing_reblogs", sa.Boolean(), nullable=False),
        sa.Column("notifying", sa.Boolean(), nullable=False),
        sa.Column("languages", sa.JSON(), nullable=True),
        sa.Column("followed_by", sa.Boolean(), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("blocked_by", sa.Boolean(), nullable=False),
        sa.Column("muting", sa.Boolean(), nullable=False),
        sa.Column("muting_notifications", sa.Boolean(), nullable=False),
        sa.Column("muting_expires_at", sa.DateTime(), nullable=True),
        sa.Column("endorsed", sa.Boolean(), nullable=False),
        sa.Column("requested", sa.Boolean(), nullable=False),
        sa.Column("requested_by", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_account_id", "target_account_id", name="uq_relationship_source_target"),
    )
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_relationships_source_account_id"), ["source_account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_relationships_target_account_id"), ["target_account_id"], unique=False)

    op.create_table(
        "scheduled_statuses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduled_statuses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scheduled_statuses_account_id"), ["account_id"], unique=False)

    op.create_table(
        "statuses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("in_reply_to_id", sa.BigInteger(), nullable=True),
        sa.Column("in_reply_to_account_id", sa.BigInteger(), nullable=True),
        sa.Column("reblog_of_id", sa.BigInteger(), nullable=True),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("spoiler_text", sa.String(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("poll_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("application_id", sa.BigInteger(), nullable=True),
        sa.Column("edit_history", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["oauth_apps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["in_reply_to_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["in_reply_to_id"],
            ["statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["polls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reblog_of_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("statuses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_statuses_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_statuses_created_at"), ["created_at"], unique=False)

    op.create_table(
        "user_lists",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("replies_policy", sa.String(), nullable=False),
        sa.Column("exclusive", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_lists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_lists_account_id"), ["account_id"], unique=False)

    op.create_table(
        "bookmarks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "status_id", name="uq_bookmark"),
    )
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookmarks_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookmarks_status_id"), ["status_id"], unique=False)

    op.create_table(
        "favourites",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "status_id", name="uq_favourite"),
    )
    with op.batch_alter_table("favourites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_favourites_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_favourites_status_id"), ["status_id"], unique=False)

    op.create_table(
        "filter_keywords",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("filter_id", sa.BigInteger(), nullable=False),
        sa.Column("keyword", sa.String(), nullable=False),
        sa.Column("whole_word", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["filter_id"],
            ["filters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("filter_keywords", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_filter_keywords_filter_id"), ["filter_id"], unique=False)

    op.create_table(
        "idempotency",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "key", name="uq_idempotency"),
    )
    with op.batch_alter_table("idempotency", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_idempotency_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_idempotency_key"), ["key"], unique=False)

    op.create_table(
        "media_attachments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("preview_url", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("blurhash", sa.String(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("from_account_id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False)

    op.create_table(
        "pins",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "status_id", name="uq_pin"),
    )
    with op.batch_alter_table("pins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pins_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_pins_status_id"), ["status_id"], unique=False)

    op.create_table(
        "status_mentions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("status_mentions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_status_mentions_status_id"), ["status_id"], unique=False)

    op.create_table(
        "status_mutes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "status_id", name="uq_status_mute"),
    )
    with op.batch_alter_table("status_mutes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_status_mutes_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_status_mutes_status_id"), ["status_id"], unique=False)

    op.create_table(
        "status_tags",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("status_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("status_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_status_tags_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_status_tags_status_id"), ["status_id"], unique=False)

    op.create_table(
        "user_list_accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("list_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["user_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_list_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_list_accounts_list_id"), ["list_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_list_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_list_accounts_list_id"))

    op.drop_table("user_list_accounts")
    with op.batch_alter_table("status_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_status_tags_status_id"))
        batch_op.drop_index(batch_op.f("ix_status_tags_name"))

    op.drop_table("status_tags")
    with op.batch_alter_table("status_mutes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_status_mutes_status_id"))
        batch_op.drop_index(batch_op.f("ix_status_mutes_account_id"))

    op.drop_table("status_mutes")
    with op.batch_alter_table("status_mentions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_status_mentions_status_id"))

    op.drop_table("status_mentions")
    with op.batch_alter_table("pins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pins_status_id"))
        batch_op.drop_index(batch_op.f("ix_pins_account_id"))

    op.drop_table("pins")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_account_id"))

    op.drop_table("notifications")
    op.drop_table("media_attachments")
    with op.batch_alter_table("idempotency", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_idempotency_account_id"))

    op.drop_table("idempotency")
    with op.batch_alter_table("filter_keywords", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filter_keywords_filter_id"))

    op.drop_table("filter_keywords")
    with op.batch_alter_table("favourites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favourites_status_id"))
        batch_op.drop_index(batch_op.f("ix_favourites_account_id"))

    op.drop_table("favourites")
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmarks_status_id"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_account_id"))

    op.drop_table("bookmarks")
    with op.batch_alter_table("user_lists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_lists_account_id"))

    op.drop_table("user_lists")
    with op.batch_alter_table("statuses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_statuses_created_at"))
        batch_op.drop_index(batch_op.f("ix_statuses_account_id"))

    op.drop_table("statuses")
    with op.batch_alter_table("scheduled_statuses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_statuses_account_id"))

    op.drop_table("scheduled_statuses")
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relationships_target_account_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_source_account_id"))

    op.drop_table("relationships")
    with op.batch_alter_table("poll_votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_poll_votes_poll_id"))

    op.drop_table("poll_votes")
    op.drop_table("poll_options")
    op.drop_table("oauth_tokens")
    with op.batch_alter_table("markers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_markers_account_id"))

    op.drop_table("markers")
    with op.batch_alter_table("filters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filters_account_id"))

    op.drop_table("filters")
    with op.batch_alter_table("domain_blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_domain_blocks_account_id"))

    op.drop_table("domain_blocks")
    with op.batch_alter_table("conversation_reads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_reads_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_reads_account_id"))

    op.drop_table("conversation_reads")
    op.drop_table("polls")
    op.drop_table("oauth_apps")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_username"))

    op.drop_table("accounts")
    # ### end Alembic commands ###
