"""add featured_tags table

Revision ID: 81d660ce78b7
Revises: 4876ba204456
Create Date: 2026-06-15 12:00:35.454495
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81d660ce78b7"
down_revision: str | None = "4876ba204456"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "featured_tags",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "name", name="uq_featured_tag"),
    )
    with op.batch_alter_table("featured_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_featured_tags_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_featured_tags_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("featured_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_featured_tags_name"))
        batch_op.drop_index(batch_op.f("ix_featured_tags_account_id"))

    op.drop_table("featured_tags")
    # ### end Alembic commands ###
