"""Metadata for mastodon_mock. Generated by metametameta — do not edit by hand."""

__all__ = [
    "__credits__",
    "__description__",
    "__keywords__",
    "__license__",
    "__readme__",
    "__requires_python__",
    "__status__",
    "__title__",
    "__version__",
]

__title__ = "mastodon_mock"
__version__ = "0.1.0"
__description__ = "Stateful Mastodon mock server that mocks the REST API with a minimal in-memory/sqlite database"
__readme__ = "README.md"
__credits__ = [{"name": "Matthew Martin", "email": "matthewdeanmartin@gmail.com"}]
__keywords__ = ["mastodon_mock"]
__license__ = "MIT"
__requires_python__ = ">=3.13"
__status__ = "3 - Alpha"
