"""Static-shape stubs for obscure/rarely-used upstream endpoints.

None of these have a Mastodon.py caller; they exist only so the mock's contract
matches upstream's path/method surface. No persistence, no real behavior —
fixed-shape responses are sufficient (see spec/openapi_support.md Phase 3/4).
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException

from mastodon_mock.deps import Config, RequiredAccount

router = APIRouter(tags=["misc"])


# --- oEmbed --------------------------------------------------------------


@router.get("/api/oembed")
def oembed(url: str, config: Config) -> dict[str, Any]:
    """Minimal OEmbed response for a status URL.

    ``author_url``/``provider_url`` must be valid URIs and ``width`` is required
    (OEmbedResponse schema) — echoing the caller-supplied ``url`` would violate
    the URI format whenever it isn't one.
    """
    del url
    base = f"https://{config.domain}"
    return {
        "type": "link",
        "version": "1.0",
        "title": "mastodon_mock",
        "author_name": "",
        "author_url": f"{base}/",
        "provider_name": "mastodon_mock",
        "provider_url": f"{base}/",
        "html": "",
        "width": 400,
        # The reconstructed OEmbedResponse schema types height as string|null.
        "height": None,
        "cache_age": 86400,
    }


# --- Collections (4.6.0, no known client usage) ---------------------------


@router.post("/api/v1/collections", status_code=200)
def create_collection(account: RequiredAccount) -> dict[str, Any]:
    """Create a collection. No persistence; echoes an empty wrapped collection."""
    del account
    return {"collection": None}


@router.get("/api/v1/collections/{collection_id}")
def get_collection(collection_id: str) -> dict[str, Any]:
    """Fetch a collection. The mock keeps no collections, so this always 404s."""
    del collection_id
    raise HTTPException(status_code=404, detail="Record not found")


@router.patch("/api/v1/collections/{collection_id}")
def update_collection(collection_id: str) -> dict[str, Any]:
    """Update a collection. The mock keeps no collections, so this always 404s."""
    del collection_id
    raise HTTPException(status_code=404, detail="Record not found")


@router.delete("/api/v1/collections/{collection_id}", status_code=200)
def delete_collection(collection_id: str) -> dict[str, Any]:
    """Delete a collection. No persistence; accepts and no-ops."""
    del collection_id
    return {}


@router.post("/api/v1/collections/{collection_id}/items", status_code=200)
def add_collection_items(collection_id: str) -> list[Any]:
    """Add items to a collection. No persistence; returns an empty list."""
    del collection_id
    return []


@router.delete("/api/v1/collections/{collection_id}/items/{item_id}", status_code=200)
def delete_collection_item(collection_id: str, item_id: str) -> dict[str, Any]:
    """Remove an item from a collection. No persistence; accepts and no-ops."""
    del collection_id, item_id
    return {}


@router.post("/api/v1/collections/{collection_id}/items/{item_id}/revoke", status_code=200)
def revoke_collection_item(collection_id: str, item_id: str) -> dict[str, Any]:
    """Revoke a collection item grant. No persistence; accepts and no-ops."""
    del collection_id, item_id
    return {}


# Path verified against mastodon.social: these are account-scoped under
# /api/v1/accounts/{id}/... and wrap the payload in `{"collections": [...]}`.
@router.get("/api/v1/accounts/{account_id}/collections")
def account_collections(account_id: str) -> dict[str, Any]:
    """List collections for an account. The mock keeps no collections."""
    del account_id
    return {"collections": []}


@router.get("/api/v1/accounts/{account_id}/in_collections")
def account_in_collections(account_id: str) -> dict[str, Any]:
    """List collections an account appears in. The mock keeps no collections."""
    del account_id
    return {"collections": []}


# --- Annual reports ("Wrapstodon") -----------------------------------------


@router.get("/api/v1/annual_reports")
def annual_reports() -> dict[str, Any]:
    """No annual reports are ever generated by the mock."""
    return {"annual_reports": []}


@router.get("/api/v1/annual_reports/{year}")
def annual_report(year: str) -> dict[str, Any]:
    """No annual reports are ever generated by the mock."""
    del year
    raise HTTPException(status_code=404, detail="Record not found")


@router.get("/api/v1/annual_reports/{year}/state")
def annual_report_state(year: str) -> dict[str, Any]:
    """Annual reports are never eligible in the mock."""
    del year
    return {"state": "ineligible"}


@router.post("/api/v1/annual_reports/{year}/generate", status_code=200)
def annual_report_generate(year: str, account: RequiredAccount) -> dict[str, Any]:
    """Accept the generation request; no report is ever produced."""
    del year, account
    return {}


@router.post("/api/v1/annual_reports/{year}/read", status_code=200)
def annual_report_read(year: str, account: RequiredAccount) -> dict[str, Any]:
    """Mark an annual report as read; no-op since none exist."""
    del year, account
    return {}


# --- Async refreshes ---------------------------------------------------


@router.get("/api/v1_alpha/async_refreshes/{refresh_id}")
def async_refresh_status(refresh_id: str) -> dict[str, Any]:
    """The mock never runs background refresh jobs; everything is already complete."""
    return {"async_refresh": {"id": refresh_id, "status": "finished"}}
